@url = https://localhost:7177
@carIdToGet = 00000000-0000-0000-0000-000000000001
@carIdToUpdate = ba9d01a5-81e7-48f4-a973-a2753eed2941

// Users
@userIdToGet = 00000000-0000-0000-0000-000000000001
@userIdToUpdate = b24141ce-a942-43b4-93e6-a5db990d50df


###
GET {{url}}/api/users/
Accept: application/json

###
GET {{url}}/api/users/{{userIdToGet}}
Accept: application/json

###
POST  {{url}}/api/users/
Content-Type: application/json

{
    "firstName": "Janek",
    "lastName": "Werbel",
    "email": "j.werbel@wp.pl",
    "phone": "+48111222333"
}

###
PUT  {{url}}/api/users/{{userIdToUpdate}}
Content-Type: application/json

{
    "firstName": "Janek",
    "lastName": "Werbel",
    "email": "j2.werbel@wp.pl",
    "phone": "+48999888777"
}

###
PUT  {{url}}/api/users/{{userIdToUpdate}}/deactivate
Content-Type: application/json


###
GET {{url}}/api/cars/
Accept: application/json

###
GET {{url}}/api/cars/{{carIdToGet}}
Accept: application/json

###
POST  {{url}}/api/cars/
Content-Type: application/json

{
    "brand": "Ferrari",
    "model": "F40",
    "productionYear": 1990,
    "registrationNumber": "TE1234",
    "mileage": 1000,
    "color": "Red",
    "fuelType": 1
}

###
PUT  {{url}}/api/cars/{{carIdToUpdate}}
Content-Type: application/json

{
    "brand": "Ferrari",
    "model": "F40",
    "productionYear": 1990,
    "registrationNumber": "TE0987",
    "mileage": 1000,
    "color": "Blue",
    "fuelType": 1
}

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/deactivate
Content-Type: application/json

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/start-hire
Content-Type: application/json

{
    "carId": "{{carIdToUpdate}}",
    "userId": "{{userIdToUpdate}}",
    "startDate": "2024-01-23",
    "endDate": "2024-01-24",
    "startMileage": 20450
}

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/end-hire
Content-Type: application/json

{
    "hireId": "c2ef1dd0-1fea-4027-a7f9-3fa2dd84b517",
    "carId": "{{carIdToUpdate}}",
    "endMileage": 21406,
    "returnDate": "2024-01-24"
}

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/remove-hire
Content-Type: application/json

{
    "hireId": "c2ef1dd0-1fea-4027-a7f9-3fa2dd84b517",
    "carId": "{{carIdToUpdate}}"
}

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/start-reservation
Content-Type: application/json

{
    "carId": "{{carIdToUpdate}}",
    "startDate": "2024-01-23",
    "endDate": "2024-01-24",
    "userId": "{{userIdToUpdate}}"
}

###
PUT   {{url}}/api/cars/{{carIdToUpdate}}/remove-reservation
Content-Type: application/json

{
    "ReservationId": "c4755dae-354a-4ec0-b584-6edccc47884c",
    "carId": "{{carIdToUpdate}}"
}